language: nix
os: osx
git:
  clone: false
before_script: git clone https://github.com/$TRAVIS_REPO_SLUG.git ~/.nixpkgs
cache:
  directories:
    - /nix/store
    - /run
script: cd ~/.nixpkgs && nix-shell --run "darwinTest"
branches:
  only:
    - master

