language: nix
os: osx
git:
  clone: false
before_script: git clone https://github.com/$TRAVIS_REPO_SLUG.git ~/.nixpkgs
cache:
  directories:
    - /nix/store
script: cd ~/.nixpkgs && nix-shell -p nixFlakes --run "nix develop --command \"darwinTest\""
branches:
  only:
    - master

