name: Bisect nixpkgs input

on:
  workflow_dispatch:

jobs:
  bisect-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - nixosConfigurations.phil.config.system.build.toplevel
          - homeManagerConfigurations.server.activationPackage
    steps:
    - uses: actions/checkout@v3
      with:
        path: system
    - name: Checkout nixpkgs
      uses: actions/checkout@v3
      with:
        repository: NixOS/nixpkgs
        fetch-depth: 0
        path: nixpkgs
    - name: Cleanup disk
      uses: curoky/cleanup-disk-action@v2.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Bisect nixpkgs flake input
      run: |
        # Assumes that HEAD points to a flake update commit and extract nixpkgs refs
        GOOD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*\([0-9a-f]\{40\}\)' -> '.*[0-9a-f]\{40\}'/\1/")
        BAD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*[0-9a-f]\{40\}' -> '.*\([0-9a-f]\{40\}\)'/\1/")
        git -C nixpkgs bisect start
        git -C nixpkgs bisect good $GOOD_REF
        git -C nixpkgs bisect bad $BAD_REF
        # Automate git bisect with nix build command
        git -C nixpkgs bisect run nix build $GITHUB_WORKSPACE/system#.${{ matrix.configuration }} --override-input nixpkgs $GITHUB_WORKSPACE/nixpkgs

  bisect-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
          - darwinConfigurations.MacBook.config.system.build.toplevel
    steps:
    - uses: actions/checkout@v3
      with:
        path: system
    - name: Checkout nixpkgs
      uses: actions/checkout@v3
      with:
        repository: NixOS/nixpkgs
        fetch-depth: 0
        path: nixpkgs
    - name: Cleanup disk
      uses: curoky/cleanup-disk-action@v2.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Bisect nixpkgs flake input
      run: |
        # Assumes that HEAD points to a flake update commit and extract nixpkgs refs
        GOOD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*\([0-9a-f]\{40\}\)' -> '.*[0-9a-f]\{40\}'/\1/")
        BAD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*[0-9a-f]\{40\}' -> '.*\([0-9a-f]\{40\}\)'/\1/")
        git -C nixpkgs bisect start
        git -C nixpkgs bisect good $GOOD_REF
        git -C nixpkgs bisect bad $BAD_REF
        # Automate git bisect with nix build command
        git -C nixpkgs bisect run nix build $GITHUB_WORKSPACE/system#.${{ matrix.configuration }} --override-input nixpkgs $GITHUB_WORKSPACE/nixpkgs
