name: "nix-darwin system build"
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # - run: nix-shell --run "darwinTest"
      - run: nix-shell --run "darwinInstall"
