name: "nix-darwin system build"
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build_darwin:
    runs-on: macos-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://kclejeune.cachix.org https://cache.nixos.org
            trusted-public-keys = kclejeune.cachix.org-1:fOCrECygdFZKbMxHClhiTS6oowOkJ/I/dh9q9b1I4ko= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Randall
        run: nix build .#darwinConfigurations.Randall.config.system.build.toplevel
  build_nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://kclejeune.cachix.org https://cache.nixos.org
            trusted-public-keys = kclejeune.cachix.org-1:fOCrECygdFZKbMxHClhiTS6oowOkJ/I/dh9q9b1I4ko= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Phil
        run: nix build .#nixosConfigurations.Phil.config.system.build.toplevel
