name: "nix-darwin system build"
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build_darwin:
    runs-on: macos-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v11
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Randall
        run: nix build .#nixosConfigurations.Randall.config.system.build.toplevel
  build_nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v11
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Phil
        run: nix build .#nixosConfigurations.Phil.config.system.build.toplevel
