name: 'system build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        host:
          - nixosConfigurations.phil.config.system.build.toplevel
          - homeManagerConfigurations.server.activationPackage
          - devShell.x86_64-linux
        include:
          - os: macos-latest
            host: darwinConfigurations.randall.config.system.build.toplevel
          - os: macos-latest
            host: devShell.x86_64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: kclejeune
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Configuration
        run: |
          # build the configuration
          nix build -v .#${{ matrix.host }}
        timeout-minutes: 120

