name: 'system build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_darwin:
    runs-on: macos-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Randall
        run: nix-shell --run "darwinBuild randall"
  build_nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Phil
        run: nix-shell --run "nixosBuild phil"
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kclejeune
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Server
        run: nix-shell --run "homeManagerBuild server"
