name: Auto Update Flake Inputs

on:
  schedule:
    # run this daily at 8am UTC, or roughly 4am eastern
    - cron: '0 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Prepare flakebot branch
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -B flakebot
      - name: Update and commit lockfile
        run: nix flake update --commit-lock-file
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: flakebot
          force: true
      - name: pull-request-action
        uses: vsoch/pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: 'flakebot'
          PULL_REQUEST_BRANCH: 'master'
          MAINTAINER_CANT_MODIFY: true
          PASS_IF_EXISTS: true
          PASS_ON_ERROR: true
          PULL_REQUEST_TITLE: 'Update Flake Inputs'
